### ISSUE TITLE
Avatar Command error with mentioning users.

### ISSUE THREAD

**Issue by NTMNathan** [Skillz4Killz/Discordeno-bot-template#10]
With the avatar command, whenever you mention someone. It will return an error in the console (see below) so fetching Someone's Avatar is not possible.

` const user = message.mentions.length ? message.mentions[0] : message.author;`

It outputs nothing other than a Failed message and Red Error Brackets.

**Comment by Skillz4Killz** [comment]
Can you try `deno cache --reload mod.ts` and see if it fixes it. Just deployed a quick fix for this.
![image](https://user-images.githubusercontent.com/23035000/82108381-0a7b5000-96fc-11ea-8d68-975f9b25b912.png)

**Comment by NTMNathan** [comment]
Yep, it is now working 👍 
Question again, does Discordeno support Bot Statuses? All I can find related to that is the `presenceUpdate` property in Events so how would that be done?

I will also make a list of bugs I come across and once enough i'll make a bug report with them all, just to ease of the clutter of bug reports I make for each bug

**Comment by Skillz4Killz** [comment]
Closing this as this issue is fixed. Moved the Bot status issue to a new on as referenced above. This is indeed missing from the lib and needs to be added in. 

Feel free to make as many issues as you like. It's actually better to have them all separate instead of 1 giant issue
