### ISSUE TITLE
defaultValue doesn't always quite work due to truthy/falsy ness

### ISSUE THREAD

**Issue by Yofou** [Skillz4Killz/Discordeno-bot-template#23]
https://github.com/Skillz4Killz/Discordeno-bot-template/blob/02012a9b20cb3b295ecd5d486ec179cf9462b4d6/src/monitors/commandHandler.ts#L67

Due to truthy/falsy, this sometimes doesn't work as expected, because all the suggested types for that property can all be falsy I think it would be fitting to change that conditional to...

`if (argument.hasOwnProperty('defaultValue')) args[argument.name] = argument.defaultValue;`
tested on my own terms worked like a charm and what I personally think is a wiser choice

**Comment by Skillz4Killz** [comment]
Good catch! Would you mind sending a PR for this 🙏

**Comment by Skillz4Killz** [comment]
Fixed in #24
