### ISSUE TITLE
The Entire Template Wont Start

### ISSUE THREAD

**Issue by GBrayJ** [Skillz4Killz/Discordeno-bot-template#39]
When running the template on VSCODE terminal you get this message "
PS C:\Users\Brayden\DiscordENO> deno run --allow-net --allow-read --quiet mod.ts
error: expected value at line 1 column 1
Imported from "https://deno.land/x/i18next@v19.6.3/i18next.js:10""

When using PM2 this
"PS C:\Users\Brayden\DiscordENO> pm2 start c:\Users\Brayden\DiscordENO\mod.ts --interpreter="deno" --interpreter-args="run --allow-net --allow-read --quiet -r"
[PM2] Applying action restartProcessId on app [mod](ids: [ 0, 1 ])
[PM2] [mod](0) ✓
[PM2] [mod](1) ✓
[PM2] Process successfully started
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ mod                │ fork     │ 31   │ online    │ 0%       │ 18.2mb   │
│ 1  │ mod                │ fork     │ 30   │ online    │ 0%       │ 18.1mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
PS C:\Users\Brayden\DiscordENO> " 
and it doesn't actually run. (With token configured)

**Comment by Skillz4Killz** [comment]
Thank you for catching this, the readme was a little outdated. With the latest changes to deno, we have begun needing more flags in order to make it all work together. `pm2 start mod.ts --interpreter="deno" --interpreter-args="run --allow-net --allow-read --no-check --config tsconfig.json --quiet -r"`

For future reference, I always keep the `scripts.yml` file updated, sometimes I forget to update the readme sorry 🙏 

If this doesn't fix the issues, I will reopen the issue for you, just leave a comment letting me know

**Comment by GBrayJ** [comment]
Ok. Thanks! 👍

**Comment by GBrayJ** [comment]
It didn't actually fix the issue. 
It still can't connect!

**Comment by GBrayJ** [comment]
It says it started, but the bot doesn't go online. Using 'Deno' just gives me the error ```
error: expected value at line 1 column 1
Imported from "https://deno.land/x/i18next@v19.6.3/i18next.js:10"
``` and doesn't work.

**Comment by GBrayJ** [comment]
If you need system settings, configs, logs, environmental settings, ect* just tell me what you need.

**Comment by GBrayJ** [comment]
The need command you left me does not work. My error message is 
```
PS C:\Users\Brayden\DiscordENO> deno run --allow-net --allow-read --no-check --config tsconfig.json --quiet
error: The following required arguments were not provided:
    <SCRIPT_ARG>...

USAGE:
    deno run <SCRIPT_ARG>... --allow-net=<allow-net> --allow-read=<allow-read> --config <FILE> --no-check --quiet

For more information try --help
```

**Comment by Skillz4Killz** [comment]
@GBrayJ Looks like you forgot to give it the file to run. At the end type `mod.ts`

**Comment by GBrayJ** [comment]
So if I do that I get this
```
PS C:\Users\Brayden\DiscordENO> deno run --allow-net --allow-read --no-check --config tsconfig.json mod.ts
Download https://x.nest.land/Discordeno@9.0.1/src/module/client.ts
Download https://x.nest.land/Discordeno@9.0.1/mod.ts
Download https://arweave.net/0HlC7Biwq9YMnvvY0T53JCusUSwIpSBfHW_YQY5KRZA/mod.ts
Download https://arweave.net/0HlC7Biwq9YMnvvY0T53JCusUSwIpSBfHW_YQY5KRZA/src/module/client.ts
error: error sending request for url (https://arweave.net/0HlC7Biwq9YMnvvY0T53JCusUSwIpSBfHW_YQY5KRZA/mod.ts): error trying to connect: received corrupt message
PS C:\Users\Brayden\DiscordENO> 
``` and it still doesn't work.

**Comment by Skillz4Killz** [comment]
After speaking to Nest.Land and Deno devs this appears to be a network issue that needs to be resolved with Deno itself. The library itself is not the issue as the same code is working on other devices.
Best place to request help for this would be at https://discord.gg/deno
