### ISSUE TITLE
The mod.ts wont start

### ISSUE THREAD

**Issue by VlaDexa** [Skillz4Killz/Discordeno-bot-template#41]
C:\Users\VlaDexa\Desktop\Projects\PutinBot\Putin>deno run --allow-net --allow-read mod.ts
Check file:///C:/Users/VlaDexa/Desktop/Projects/PutinBot/Putin/mod.ts
Beginning Bot Startup Process. This can take a little bit depending on your system. Loading now...
error: Uncaught NotFound: Не удается найти указанный файл. (os error 2)
    at Object.jsonOpSync (core.js:247:13)
    at Object.realPathSync (deno:cli/rt/30_fs.js:139:17)
    at mod.ts:50:34
    at Array.map (<anonymous>)
    at mod.ts:49:3

The russian bit translates to: "System can't find mentioned file"

**Comment by VlaDexa** [comment]
Also had a lot of these kind of errors

error: Uncaught TypeError: TS2339 [ERROR]: Property 'tag' does not exist on type 'MemberCreatePayload'.
      .setAuthor(member.tag, member.avatarURL)
                        ~~~
    at file:///C:/Users/VlaDexa/Desktop/Projects/PutinBot/Putin/src/commands/add.ts#0:22:25

TS2339 [ERROR]: Property 'avatarURL' does not exist on type 'MemberCreatePayload'.
      .setAuthor(member.tag, member.avatarURL)
                                    ~~~~~~~~~
    at file:///C:/Users/VlaDexa/Desktop/Projects/PutinBot/Putin/src/commands/add.ts#0:22:37

Found 2 errors.

**Comment by Skillz4Killz** [comment]
@VlaDexa The first one should be fixed by doing this in ur code https://github.com/Skillz4Killz/Discordeno-bot-template/commit/f575587f9e453225464b13a44977861e2b473599

The second one just is happening because you are missing some of the flags when running it.
