### ISSUE TITLE
prefix command never responds when arguments are missing

### ISSUE THREAD

**Issue by ayntee** [Skillz4Killz/Discordeno-bot-template#50]
When prefix command is ran without any arguments, the bot never sends the message "please provide a prefix" to the channel. However, it does log that the arguments are missing in the console. The bot has sufficient permissions to send messages... I have tried this with latest Discordeno version (raw GitHub, nest.land@latest, and the current version)

![image](https://user-images.githubusercontent.com/34645569/99249758-04d60280-2824-11eb-8bcb-da52248da525.png)

**Comment by itohatweb** [comment]
Should be resolved. ( #62 PR)
