### ISSUE TITLE
Save Running Tasks in botCache?

### ISSUE THREAD

**Issue by itohatweb** [Skillz4Killz/Discordeno-bot-template#60]
Should the running tasks be saved in `botCache.runningTasks` instead of using an random Array?

**Comment by Skillz4Killz** [comment]
Personally i like the current way as it makes it a little more difficult for beginners to mess it up and this repo is designed for them. But im not against moving it if you have any reason ud want it there

**Comment by ayntee** [comment]
+1 for this, it looks more organized this way.

**Comment by itohatweb** [comment]
Thought the same way.
